// Auth
export const USER_LOADED = 'USER_LOADED';
export const USER_LOADING = 'USER_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// Errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Picklist
export const GET_PICKLIST = 'GET_PICKLIST';
export const GET_PICKLISTS = 'GET_PICKLISTS';
export const PICKLISTS_ERROR = 'PICKLISTS_ERROR';
export const ADD_PICKLIST = 'ADD_PICKLIST';
export const UPDATE_PICKLIST = 'UPDATE_PICKLIST';
export const SUBMIT_PICKLIST = 'SUBMIT_PICKLIST';
export const DELETE_PICKLIST = 'DELETE_PICKLIST';
export const GET_CURRENT_PICKLIST = 'GET_CURRENT_PICKLIST';
export const CLEAR_CURRENT_PICKLIST = 'CLEAR_CURRENT_PICKLIST';
export const FILTER_PICKLISTS = 'FILTER_PICKLISTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const PICKLISTS_LOADING = 'PICKLISTS_LOADING';

// Library
export const GET_ITEM = 'GET_ITEM';
export const GET_LIBRARY = 'GET_LIBRARY';
export const ITEMS_ERROR = 'ITEMS_ERROR';
export const ADD_LIBRARY_ITEM = 'ADD_ITEM';
export const UPDATE_LIBRARY_ITEM = 'UPDATE_ITEM';
export const DELETE_LIBRARY_ITEM = 'DELETE_ITEM';
export const SEARCH_LIBRARY = 'SEARCH_LIBRARY';
export const CLEAR_LIBRARY_SEARCH = 'CLEAR_LIBRARY_SEARCH';
export const SET_LIBRARY_CURRENT = 'SET_LIBRARY_CURRENT';
export const CLEAR_LIBRARY_CURRENT = 'CLEAR_LIBRARY_CURRENT';
export const LIBRARY_LOADING = 'LIBRARY_LOADING';

// Loading/Current
export const SET_LOADING = 'SET_LOADING';
export const SET_CURRENT = 'SET_CURRENT';
